const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let sb,user=null,profile=null,goal=null,entries=[],weights=[],selectedDate=localDate(),monthCursor=new Date(),goalType='lose',editing=null,recognized=[];
function localDate(d=new Date()){let x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function fmt(d){return new Date(d+'T12:00').toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}
function ageOn(b,d=new Date()){let x=new Date(b+'T12:00'),a=d.getFullYear()-x.getFullYear();if(d<new Date(d.getFullYear(),x.getMonth(),x.getDate()))a--;return a}
function plan(){if(!profile||!goal)return null;let w=latestWeight(goal.start_date)?.weight||goal.start_weight,age=ageOn(profile.birth_date),sex=profile.sex,b=10*w+6.25*profile.height_cm-5*age+(sex==='male'?5:sex==='female'?-161:-78),maint=b*profile.activity_factor,days=Math.max(1,(new Date(goal.target_date+'T12:00')-new Date(goal.start_date+'T12:00'))/86400000),kg=goal.target_weight-goal.start_weight,delta=kg*7700/days;if(goal.goal_type==='maintain')delta=0;if(goal.goal_type==='muscle')delta=Math.max(150,Math.min(400,delta));if(goal.goal_type==='lose')delta=Math.min(-150,Math.max(-700,delta));return{calories:Math.round((maint+delta)/10)*10,protein:Math.round(w*(goal.goal_type==='muscle'?1.8:goal.goal_type==='lose'?1.6:1.4)),maint:Math.round(maint),weekly:kg/(days/7)}}
function latestWeight(before){let a=weights.filter(x=>!before||x.measured_on<=before).sort((a,b)=>a.measured_on.localeCompare(b.measured_on));return a.at(-1)}
function dayEntries(d=selectedDate){return entries.filter(e=>e.entry_date===d)} function sums(a){return a.reduce((s,e)=>({k:s.k+(+e.kcal||0),p:s.p+(+e.protein_g||0)}),{k:0,p:0})}
function statusFor(d){let p=plan();if(!p)return '';let s=sums(dayEntries(d)),ratio=s.k/p.calories;if(!s.k)return '';return ratio>=.9&&ratio<=1.08?'green':ratio>=.8&&ratio<=1.18?'yellow':'red'}
async function init(){
  sb=window.netlifyStore;
  let {data}=await sb.auth.getSession();
  user=data.session?.user||null;
  authUI();
  if(user) await loadAll();
}
function authUI(){
  let on=!!user;
  $('#signedOut').classList.toggle('hidden',on);
  $('#signedIn').classList.toggle('hidden',!on);
  $('#syncState').textContent=on?'Cloud aktiv':'nicht angemeldet';
  if(on) $('#userEmail').textContent=user.email;
}
async function authAction(kind){
  let email=$('#authEmail').value.trim(), password=$('#authPassword').value;
  if(!email||!password) return $('#authMessage').textContent='Bitte E-Mail und Passwort eingeben.';
  let btn=kind==='login'?$('#loginBtn'):$('#signupBtn');
  btn.disabled=true; $('#authMessage').textContent=kind==='login'?'Anmeldung läuft …':'Konto wird erstellt …';
  try{
    let d=await api('/api/'+kind,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});
    if(kind==='signup' && d.needsConfirmation){
      $('#authMessage').textContent='Konto erstellt. Bitte bestätige die E-Mail und logge dich danach ein.';
    }else{
      let me=await api('/api/me'); user=me.user; authUI(); await loadAll();
      $('#authMessage').textContent='';
    }
  }catch(e){ $('#authMessage').textContent='Fehler: '+e.message }
  finally{btn.disabled=false}
}
$('#loginBtn').onclick=()=>authAction('login');
$('#signupBtn').onclick=()=>authAction('signup');
$('#logoutBtn').onclick=()=>sb.auth.signOut();
async function loadAll(){let [pr,go,en,we]=await Promise.all([sb.from('profiles').select('*').eq('user_id',user.id).maybeSingle(),sb.from('goals').select('*').eq('user_id',user.id).eq('status','active').order('created_at',{ascending:false}).limit(1).maybeSingle(),sb.from('food_entries').select('*').eq('user_id',user.id).order('created_at'),sb.from('weight_entries').select('*').eq('user_id',user.id).order('measured_on')]);profile=pr.data;goal=go.data;entries=en.data||[];weights=we.data||[];if(!profile){$('#onboarding').classList.remove('hidden');$('#mainUI').classList.add('hidden')}else if(!goal){$('#goalSetup').classList.remove('hidden');$('#mainUI').classList.add('hidden');prefillGoal()}else{$('#onboarding').classList.add('hidden');$('#goalSetup').classList.add('hidden');$('#mainUI').classList.remove('hidden');selectedDate=localDate();render()}}
$('#saveProfileBtn').onclick=async()=>{let data={user_id:user.id,birth_date:$('#birthDate').value,sex:$('#sex').value,height_cm:+$('#height').value,activity_factor:+$('#activity').value,conditions:$('#conditions').value.trim(),uric_mode:$('#uricMode').checked};if(!data.birth_date||!data.height_cm||!$('#startWeight').value)return alert('Bitte Geburtsdatum, Größe und aktuelles Gewicht eintragen.');let {error}=await sb.from('profiles').upsert(data);if(error)return alert(error.message);await sb.from('weight_entries').insert({user_id:user.id,measured_on:localDate(),weight:+$('#startWeight').value});profile=data;weights=[{measured_on:localDate(),weight:+$('#startWeight').value}];$('#onboarding').classList.add('hidden');$('#goalSetup').classList.remove('hidden');prefillGoal()};
function prefillGoal(){let w=latestWeight()?.weight||70;$('#goalWeight').value=w-5;$('#goalDate').value=localDate(new Date(Date.now()+180*86400000));goalType='lose';$$('[data-goal]').forEach(x=>x.classList.toggle('active',x.dataset.goal===goalType));previewGoal()}
$$('[data-goal]').forEach(b=>b.onclick=()=>{goalType=b.dataset.goal;$$('[data-goal]').forEach(x=>x.classList.toggle('active',x===b));previewGoal()});$('#goalWeight').oninput=$('#goalDate').oninput=previewGoal;
function previewGoal(){if(!profile||!$('#goalDate').value)return;let w=latestWeight()?.weight||+$('#startWeight').value||70,tmp={goal_type:goalType,start_weight:w,start_date:localDate(),target_weight:+$('#goalWeight').value,target_date:$('#goalDate').value},old=goal;goal=tmp;let p=plan();goal=old;$('#planPreview').innerHTML=`Geschätzter Erhaltungsbedarf: <b>${p.maint} kcal/Tag</b><br>Startplan: <b>${p.calories} kcal/Tag</b> · <b>${p.protein} g Protein</b><br>Erforderlicher Gewichtsverlauf: <b>${p.weekly>=0?'+':''}${p.weekly.toFixed(2)} kg/Woche</b>. Kalorien sind eine Startschätzung und werden anhand des Gewichtsverlaufs überprüft.`}
$('#saveGoalBtn').onclick=async()=>{let w=latestWeight()?.weight;if(!w||!$('#goalDate').value)return;await sb.from('goals').update({status:'archived'}).eq('user_id',user.id).eq('status','active');let data={user_id:user.id,goal_type:goalType,start_weight:w,start_date:localDate(),target_weight:+$('#goalWeight').value,target_date:$('#goalDate').value,status:'active'};let {data:g,error}=await sb.from('goals').insert(data).select().single();if(error)return alert(error.message);goal=g;$('#goalSetup').classList.add('hidden');$('#mainUI').classList.remove('hidden');render()};
$('#profileBtn').onclick=()=>{if(!user)return;$('#onboarding').classList.toggle('hidden');if(profile){$('#birthDate').value=profile.birth_date;$('#sex').value=profile.sex;$('#height').value=profile.height_cm;$('#activity').value=profile.activity_factor;$('#conditions').value=profile.conditions||'';$('#uricMode').checked=profile.uric_mode;$('#startWeight').value=latestWeight()?.weight||''}};
function render(){let p=plan(),a=dayEntries(),s=sums(a);$('#dayPicker').value=selectedDate;$('#dayTitle').textContent=fmt(selectedDate);$('#goalSummary').textContent=`${goal.goal_type==='lose'?'Fett reduzieren':goal.goal_type==='muscle'?'Muskeln aufbauen + zunehmen':'Gewicht halten'} · ${goal.target_weight} kg bis ${new Date(goal.target_date+'T12:00').toLocaleDateString('de-DE')}`;$('#kcalLabel').textContent=`${Math.round(s.k)} / ${p.calories} kcal · ${Math.round(s.k/p.calories*100)||0}%`;$('#proteinLabel').textContent=`${Math.round(s.p)} / ${p.protein} g · ${Math.round(s.p/p.protein*100)||0}%`;$('#kcalBar').style.width=Math.min(100,s.k/p.calories*100)+'%';$('#proteinBar').style.width=Math.min(100,s.p/p.protein*100)+'%';$('#uricMetric').classList.toggle('hidden',!profile.uric_mode);$('#uricLabel').textContent=a.some(e=>e.uric_level==='red')?'🔴 eher ungünstig':a.some(e=>e.uric_level==='yellow')?'🟡 gemischt':'🟢 unauffällig';$('#entries').innerHTML=a.length?a.map(e=>`<div class="entry"><div><b>${escapeHtml(e.label)}</b><br><small>${escapeHtml(e.amount_text||'')} · ${Math.round(e.kcal)} kcal · ${Math.round(e.protein_g||0)} g Protein</small></div><button data-edit="${e.id}">Bearbeiten</button></div>`).join(''):'<p class="muted">Noch nichts eingetragen. Sprich einfach ein, was du gegessen oder getrunken hast.</p>';$$('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));renderWeek();renderCalendar();renderWeights()}
$('#dayPicker').onchange=e=>{selectedDate=e.target.value;render()};
function openAdd(voice){$('#entryDialogTitle').textContent=`Ergänzen · ${new Date(selectedDate+'T12:00').toLocaleDateString('de-DE')}`;$('#entryText').value='';$('#speechStatus').textContent='';entryDialog.showModal();if(voice)setTimeout(startRecognition,200)}$('#voiceAdd').onclick=()=>openAdd(true);$('#typeAdd').onclick=()=>openAdd(false);$('#startMic').onclick=startRecognition;
function startRecognition(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#speechStatus').textContent='Dieser Browser unterstützt die direkte Spracheingabe nicht. Du kannst stattdessen tippen.';return}let r=new SR();r.lang='de-DE';r.interimResults=true;r.continuous=true;let final='';$('#speechStatus').textContent='🎙️ Ich höre zu …';r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){let t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t+' ';else interim+=t}$('#entryText').value=(final+interim).trim()};r.onerror=e=>$('#speechStatus').textContent='Mikrofon: '+e.error+'. Du kannst weiter tippen.';r.onend=()=>$('#speechStatus').textContent='Aufnahme beendet. Prüfe den Text und tippe auf Analysieren.';try{r.start()}catch{}}
async function coach(action,text=''){let res=await fetch('/api/coach',{credentials:'same-origin',method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,text,profile,goal,plan:plan(),selectedDate,entries:dayEntries(),weekEntries:weekEntries(),weights})});let raw=await res.text();if(!res.ok)throw Error(JSON.parse(raw).error||raw);return JSON.parse(raw)}
$('#analyzeEntry').onclick=async()=>{let text=$('#entryText').value.trim();if(!text)return;let b=$('#analyzeEntry');b.disabled=true;b.textContent='KI analysiert …';try{let d=await coach('parse_food',text);recognized=d.items||[];entryDialog.close();renderReview();reviewDialog.showModal()}catch(e){alert('Analyse fehlgeschlagen: '+e.message)}finally{b.disabled=false;b.textContent='Analysieren'}};
function renderReview(){$('#reviewItems').innerHTML=recognized.map((x,i)=>`<div class="reviewrow" data-i="${i}"><label class="check"><input type="checkbox" checked class="keep"> übernehmen</label><div class="grid"><input class="rl" value="${escapeAttr(x.label)}"><input class="ra" value="${escapeAttr(x.amount_text||'')}"><input class="rk" type="number" value="${Math.round(x.kcal||0)}"></div><small>Protein <input class="rp" style="width:90px" type="number" step=".1" value="${x.protein_g||0}"> g · Schätzung: ${escapeHtml(x.confidence||'mittel')}</small></div>`).join('')}
$('#saveReviewed').onclick=async()=>{let rows=$$('.reviewrow'),payload=rows.filter(r=>r.querySelector('.keep').checked).map(r=>({user_id:user.id,entry_date:selectedDate,label:r.querySelector('.rl').value,amount_text:r.querySelector('.ra').value,kcal:+r.querySelector('.rk').value,protein_g:+r.querySelector('.rp').value,uric_level:recognized[+r.dataset.i].uric_level||'green',source_text:$('#entryText').value}));if(payload.length){let {error}=await sb.from('food_entries').insert(payload);if(error)return alert(error.message)}reviewDialog.close();await refreshEntries();await updateDayConclusion()};
function openEdit(id){editing=entries.find(x=>x.id===id);$('#editLabel').value=editing.label;$('#editAmount').value=editing.amount_text||'';$('#editKcal').value=editing.kcal;$('#editProtein').value=editing.protein_g||0;editDialog.showModal()}$('#saveEdit').onclick=async()=>{let {error}=await sb.from('food_entries').update({label:$('#editLabel').value,amount_text:$('#editAmount').value,kcal:+$('#editKcal').value,protein_g:+$('#editProtein').value,updated_at:new Date().toISOString()}).eq('id',editing.id).eq('user_id',user.id);if(error)return alert(error.message);editDialog.close();await refreshEntries();await updateDayConclusion()};$('#deleteEntry').onclick=async()=>{if(!confirm('Diesen Eintrag wirklich löschen?'))return;await sb.from('food_entries').delete().eq('id',editing.id).eq('user_id',user.id);editDialog.close();await refreshEntries();await updateDayConclusion()};
async function refreshEntries(){let {data}=await sb.from('food_entries').select('*').eq('user_id',user.id).order('created_at');entries=data||[];render()}
async function updateDayConclusion(){let box=$('#dayConclusion');box.textContent='KI erstellt das Fazit …';try{let d=await coach('day_feedback');box.textContent=d.answer;await sb.from('day_summaries').upsert({user_id:user.id,summary_date:selectedDate,status:statusFor(selectedDate),summary:d.answer,updated_at:new Date().toISOString()},{onConflict:'user_id,summary_date'})}catch(e){box.textContent='Fazit konnte nicht erstellt werden: '+e.message}}$('#finishDay').onclick=updateDayConclusion;$('#tipsBtn').onclick=async()=>{coachAnswer.textContent='Coach denkt nach …';coachDialog.showModal();try{let d=await coach('day_tips');coachAnswer.textContent=d.answer}catch(e){coachAnswer.textContent='Coach konnte nicht antworten: '+e.message}};
function monday(d=new Date(selectedDate+'T12:00')){let x=new Date(d),n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);return x}function weekEntries(){let m=monday(),e=new Date(m);e.setDate(e.getDate()+6);return entries.filter(x=>x.entry_date>=localDate(m)&&x.entry_date<=localDate(e))}function renderWeek(){let m=monday(),p=plan(),days=[];for(let i=0;i<7;i++){let d=new Date(m);d.setDate(m.getDate()+i);let ds=localDate(d),st=statusFor(ds);days.push(`<button class="daydot ${st}" data-day="${ds}">${['Mo','Di','Mi','Do','Fr','Sa','So'][i]}<br>${d.getDate()}</button>`)}$('#weekDays').innerHTML=days.join('');$$('[data-day]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.day;render()});let s=sums(weekEntries()),count=7;$('#weekStats').innerHTML=`<p>Ø ${Math.round(s.k/count)} / ${p.calories} kcal pro Tag · Ø ${Math.round(s.p/count)} / ${p.protein} g Protein</p>`;let stats=[...Array(7)].map((_,i)=>{let d=new Date(m);d.setDate(m.getDate()+i);return statusFor(localDate(d))}),r=stats.filter(x=>x==='red').length,y=stats.filter(x=>x==='yellow').length;$('#weekLight').textContent=r>=3?'🔴':r||y>=3?'🟡':'🟢';$('#weekTitle').textContent='KW '+weekNumber(m)}function weekNumber(d){let x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));let y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}$('#weekFeedback').onclick=async()=>{let b=$('#weekConclusion');b.textContent='KI erstellt den Wochenrückblick …';try{let d=await coach('week_feedback');b.textContent=d.answer}catch(e){b.textContent='Wochenfazit konnte nicht erstellt werden: '+e.message}};
function renderCalendar(){let y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('#monthTitle').textContent=new Date(y,m,1).toLocaleDateString('de-DE',{month:'long',year:'numeric'});let first=new Date(y,m,1),offset=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate(),h='';for(let i=0;i<offset;i++)h+='<div></div>';for(let d=1;d<=last;d++){let ds=localDate(new Date(y,m,d)),st=statusFor(ds);h+=`<button class="calday ${st}" data-cal="${ds}">${d}<small>${st==='green'?'●':st==='yellow'?'●':st==='red'?'●':''}</small></button>`}$('#calendarGrid').innerHTML=h;$$('[data-cal]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.cal;showView('today');render()})}$('#prevMonth').onclick=()=>{monthCursor.setMonth(monthCursor.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{monthCursor.setMonth(monthCursor.getMonth()+1);renderCalendar()};
$('#addWeight').onclick=async()=>{let d=$('#weightDate').value,w=+$('#weightValue').value;if(!d||!w)return;let {error}=await sb.from('weight_entries').upsert({user_id:user.id,measured_on:d,weight:w},{onConflict:'user_id,measured_on'});if(error)return alert(error.message);let {data}=await sb.from('weight_entries').select('*').eq('user_id',user.id).order('measured_on');weights=data||[];renderWeights()};function renderWeights(){$('#weightDate').value=localDate();$('#weightList').innerHTML=weights.slice().reverse().slice(0,8).map(x=>`<div class="entry"><span>${new Date(x.measured_on+'T12:00').toLocaleDateString('de-DE')}</span><b>${x.weight} kg</b></div>`).join('');let svg=$('#weightChart');if(!goal||weights.length<1){svg.innerHTML='';return}let pts=weights.filter(x=>x.measured_on>=goal.start_date&&x.measured_on<=goal.target_date),all=[...pts.map(x=>x.weight),goal.start_weight,goal.target_weight],min=Math.min(...all)-1,max=Math.max(...all)+1,start=new Date(goal.start_date+'T12:00').getTime(),end=new Date(goal.target_date+'T12:00').getTime(),X=d=>40+(new Date(d+'T12:00').getTime()-start)/(end-start)*520,Y=w=>220-(w-min)/(max-min)*180,actual=pts.map(x=>`${X(x.measured_on)},${Y(x.weight)}`).join(' ');svg.innerHTML=`<line x1="${X(goal.start_date)}" y1="${Y(goal.start_weight)}" x2="${X(goal.target_date)}" y2="${Y(goal.target_weight)}" stroke="#999" stroke-dasharray="8 6" stroke-width="3"/><polyline points="${actual}" fill="none" stroke="#173f31" stroke-width="4"/>${pts.map(x=>`<circle cx="${X(x.measured_on)}" cy="${Y(x.weight)}" r="5" fill="#173f31"/>`).join('')}<text x="40" y="245" font-size="12">Start</text><text x="520" y="245" font-size="12">Ziel</text>`}
$$('.tabs button').forEach(b=>b.onclick=()=>showView(b.dataset.view));function showView(v){$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));['today','calendar','weight'].forEach(x=>$('#'+x+'View').classList.toggle('hidden',x!==v))}function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;')}
init();